name: messages_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: any

  auto_route: ^7.4.0
  get_it: ^7.6.0
  
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4

flutter:

  uses-material-design: true
